# Arthimatic Function

In [2]:
import numpy as np
x=np.array([1,2,3,4])
new1=x.astype(float)
print(x)
print(new1)
x=np.array([1,2,3,4,5])
print(np.sqrt(x))
var=np.array([1,2,4,5])
print(np.max(var),np.argmax(var))
print(np.min(var),np.argmin(var))
var=np.array([[1,2,3],[4,5,6]])
print("a")
print(np.min(var,axis=0),np.argmax(var))
print("b")

[1 2 3 4]
[1. 2. 3. 4.]
[1.         1.41421356 1.73205081 2.         2.23606798]
5 3
1 0
a
[1 2 3] 5
b
