# Boardcasting

In [2]:
import numpy as np


var1=np.array([1,2,3])
print(var1.shape)
print(var1)
var2=np.array([[1],[2],[3]])
print(var2.shape)
print(var2)
var3=var1+var2
print(var3.shape)
print(var3)
x=np.array([[1],[2]])
print(x.shape)
y=np.array([[1,2,3],[4,5,6]])
print(y.shape)
print(x+y)

(3,)
[1 2 3]
(3, 1)
[[1]
 [2]
 [3]]
(3, 3)
[[2 3 4]
 [3 4 5]
 [4 5 6]]
(2, 1)
(2, 3)
[[2 3 4]
 [6 7 8]]


# Shape

In [3]:
var=np.array([[1,2,3],[4,5,6]])
print(var)
print()
print(var.shape)
var1=np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print(var1.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)
[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


# Reshape

In [4]:
var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var2)
print(var2.ndim)
x=var2.reshape(2,3,2)
print(x) 
one=x.reshape(-1)
print(one)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
